PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: null
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: a7as.com
    exposer: Ingress
    http: "true"
global:
  extraEnv: |
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
  gateway:
    annotations:
      certmanager.k8s.io/issuer: letsencrypt-prod
    domain: REPLACEME
    host: activiti-cloud-gateway.{{ .Release.Namespace }}.{{ template "common.gateway-domain"
      . }}
    http: "true"
    tlsacme: "false"
  keycloak:
    client: activiti
    extraEnv: |
      # - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      #   value: "false"
    host: ""
    realm: activiti
    resource: activiti
    url: ""
  registryPullSecrets: []
jenkins:
  Servers:
    Global: {}
  enabled: null
prow: {}
